### ISSUE TITLE
[OSU api 相关] 用Coosu封装 或 重新考虑整理`API`内的结构

### ISSUE THREAD

**Issue by Milkitic** [desu-life/desu_life_backend#5]
![image](https://github.com/desu-life/desu_life_backend/assets/24785749/86abde92-8e02-494b-a42c-8ff90249f0ea)
现在的结构太套娃了

可以整理一下或者完善一下https://github.com/Coosu/Coosu/tree/master/Coosu.Api 用这个

**Comment by Monodesu** [comment]
#7
